AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  StackTagName:
    Type: String
    Description: Stack Name
    Default: aws-lambda-java-basic-service
  EnvironmentTagName:
    Type: String
    Description: Environment Name
    Default: dev

Resources:
  CreateNewMemoryCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-CreateNewMemoryCardFunction
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: CreateNewMemoryCard
      CodeUri: build/distributions/java-base-lambda-service-1.0.0-SNAPSHOT.zip
      Handler: io.theclouddeveloper.memorycards.MemoryCardsHandler::handleCreateNewMemoryCardRequest
      Runtime: java11
      MemorySize: 512
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref MemoryCardsTable
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          TABLE_NAME: !Ref MemoryCardsTable
          TABLE_ARN: !GetAtt MemoryCardsTable.Arn
          REGION: "eu-west-1"
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /memory-cards
            Method: POST

  MemoryCardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: author
          AttributeType: S
        - AttributeName: category_createdTimestamp
          AttributeType: S
        - AttributeName: createdTimestamp
          AttributeType: S
        - AttributeName: uuid
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: author
          KeyType: HASH
        - AttributeName: category_createdTimestamp
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: createdTimestampIndex
          KeySchema:
            - AttributeName: author
              KeyType: HASH
            - AttributeName: createdTimestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: idIndex
          KeySchema:
            - AttributeName: uuid
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
